name: Actions

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Buld dev image
        run: docker build . -f Dockerfile.dev -t ldc-musl
      - name: Run unittest
        run: docker run --rm -v $PWD:/workdir --workdir /workdir ldc-musl ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary and Docker image
        run: |
          docker run --rm -v $PWD:/workdir --workdir /workdir ldc-musl ldc2 -mtriple=x86_64-alpine-linux-musl -static -O -release zatsu-cwl-generator.d
          docker build . -f Dockerfile -t ttanjo/zatsu-cwl-generator:latest
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-linux-x86_64
          path: zatsu-cwl-generator
      - name: Upload the Docker image to Dockerhub
        if: github.event_name == 'push'
        run: |
          echo $DOCKER_TOKEN | docker login -u ttanjo --password-stdin
          docker push ttanjo/zatsu-cwl-generator:latest
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install ldc
        run: brew install ldc
      - name: Run unittest
        run: ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary
        run: ldc2 -O -release zatsu-cwl-generator.d
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-macos
          path: zatsu-cwl-generator

  release:
    needs: [build-docker, build-mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 
      - name: print values
        run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: create release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: skx/github-action-publish-binaries@release-0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zatsu-cwl-generator-*'
      - name: create tagged docker image
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          tag=$(basename $GITHUB_REF)
          docker pull ttanjo/zatsu-cwl-generator
          echo $DOCKER_TOKEN | docker login -u ttanjo --password-stdin
          docker tag ttanjo/zatsu-cwl-generator:latest ttanjo/zatsu-cwl-generator:$tag
          docker push ttanjo/zatsu-cwl-generator:$tag
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
