name: Actions

on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'
  pull_request: {}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Buld dev image
        run: docker build . -f dev.Dockerfile -t ldc-musl
      - name: Run unittest
        run: docker run --rm -v $PWD:/workdir --workdir /workdir ldc-musl ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary and Docker image
        run: |
          docker run --rm -v $PWD:/workdir --workdir /workdir ldc-musl ldc2 -mtriple=x86_64-alpine-linux-musl -static -O -release zatsu-cwl-generator.d
          docker build . -f Dockerfile -t ttanjo/zatsu-cwl-generator:latest
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-linux-x86_64
          path: zatsu-cwl-generator
      - name: Upload the Docker image to Dockerhub
        if: success()
        run: |
          echo $DOCKER_TOKEN | docker login -u ttanjo --password-stdin
          docker push ttanjo/zatsu-cwl-generator:latest
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install ldc
        run: brew install ldc
      - name: Run unittest
        run: ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary
        run: ldc2 -O -release zatsu-cwl-generator.d
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-osx-x86_64
          path: zatsu-cwl-generator

  stub:
    needs: [build-docker, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Download binary for macOS
        uses: actions/download-artifact@v1.0.0
        with:
          name: zatsu-cwl-generator-osx-x86_64
      - run: |
          ls -l
          ls zatsu-cwl-generator-osx-x86_64

  release:
    needs: [build-docker, build-mac]
    runs-on: ubuntu-latest
    if: github.event_name == 'create'
    steps:
      - name: Download binary for macOS
        uses: actions/download-artifact@v1.0.0
        with:
          name: zatsu-cwl-generator-osx-x86_64
      - name: Archive binary for macOS
        run: |
          ver="${GITHUB_REF##*/}"
          mv zatsu-cwl-generator-osx-x86_64 zatsu-cwl-generator
          tar Jcf zatsu-cwl-generator-${ver}-osx-x86_64.tar.xz zatsu-cwl-generator
      - name: Download binary for Linux
        uses: actions/download-artifact@v1.0.0
        with:
          name: zatsu-cwl-generator-linux-x86_64
      - name: Archive binary for Linux
        run: |
          ver="${GITHUB_REF##*/}"
          mv zatsu-cwl-generator-linux-x86_64 zatsu-cwl-generator
          tar Jcf zatsu-cwl-generator-${ver}-linux-x86_64.tar.xz zatsu-cwl-generator
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-') }}
          files: zatsu-cwl-generator-*-x86_64.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tagged docker image
        run: |
          tag="${GITHUB_REF##*/}"
          docker pull ttanjo/zatsu-cwl-generator
          echo $DOCKER_TOKEN | docker login -u ttanjo --password-stdin
          docker tag ttanjo/zatsu-cwl-generator:latest ttanjo/zatsu-cwl-generator:$tag
          docker push ttanjo/zatsu-cwl-generator:$tag
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
