name: Actions

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ttanjo/ldc-ubuntu-musl:1.17.0
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run unittest
        run: ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary
        run: ldc2 -mtriple=x86_64-alpine-linux-musl -static -O -release zatsu-cwl-generator.d
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-linux-x86_64
          path: zatsu-cwl-generator

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: mihails-strasuns/setup-dlang@v0.3.0
        with:
          compiler: ldc-1.17.0
      - name: Run unittest
        run: ldc2 -main -unittest -run zatsu-cwl-generator.d
      - name: Build the binary
        run: ldc2 -O -release zatsu-cwl-generator.d
      - uses: actions/upload-artifact@v1
        with:
          name: zatsu-cwl-generator-osx-x86_64
          path: zatsu-cwl-generator

  release:
    needs: [build-docker, build-mac]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startswith(github.ref, 'refs/tags')
    steps:
      - name: Download binary for macOS
        uses: actions/download-artifact@v1.0.0
        with:
          name: zatsu-cwl-generator-osx-x86_64
      - name: Archive binary for macOS
        run: |
          ver="${GITHUB_REF##*/}"
          mv zatsu-cwl-generator-osx-x86_64/zatsu-cwl-generator .
          tar Jcf zatsu-cwl-generator-${ver}-osx-x86_64.tar.xz zatsu-cwl-generator
      - name: Download binary for Linux
        uses: actions/download-artifact@v1.0.0
        with:
          name: zatsu-cwl-generator-linux-x86_64
      - name: Archive binary for Linux
        run: |
          ver="${GITHUB_REF##*/}"
          cp -f zatsu-cwl-generator-linux-x86_64/zatsu-cwl-generator .
          tar Jcf zatsu-cwl-generator-${ver}-linux-x86_64.tar.xz zatsu-cwl-generator
      - name: Compare the version string with the tag
        if: "!contains(github.ref, '-')"
        run: |
          chmod +x zatsu-cwl-generator
          git_tag="${GITHUB_REF##*/}"
          binary_ver=$(./zatsu-cwl-generator -v | cut -d ' ' -f 2)
          echo "git tag: ${git_tag}, binary version: ${binary_ver}"
          test "$git_tag" = "$binary_ver"
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: success() || cancelled() # release or prerelease
        with:
          prerelease: ${{ contains(github.ref, '-') }}
          files: zatsu-cwl-generator-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
        if: "!contains(github.ref, '-') && success()" # release only
        with:
          fetch-depth: 1
      - name: Create docker images
        if: success() # release only
        run: |
          tag="${GITHUB_REF##*/}"
          mv zatsu-cwl-generator-linux-x86_64/zatsu-cwl-generator .
          docker build . -f Dockerfile -t ttanjo/zatsu-cwl-generator:latest
          echo $DOCKER_TOKEN | docker login -u ttanjo --password-stdin
          docker tag ttanjo/zatsu-cwl-generator:latest ttanjo/zatsu-cwl-generator:$tag
          docker push ttanjo/zatsu-cwl-generator:latest
          docker push ttanjo/zatsu-cwl-generator:$tag
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
